# An Introduction to Decision Theory

Imagine you have an electrical contractor who has to decide how to wire new houses. They have options of 15, 20, and 30-amp wire. The higher the capacity of the wire, the more expensive it is for them. However, should the family moving into the new house ever exceed the rating of the wire, it will cause burnouts and they will have to eat the cost of rewiring the house. It will also damage their relationship with their business partners to have families constantly complaining about their work.

Taking this information, they construct a table with the loss that their business would experience depending on their actions and the peak amperage of a particular family. Columns represent the set of actions available to the electrical contractor, $A$. Rows represent the set of possible states of nature that a particular family can have, $\theta$.

#### Loss Table
| | | Actions | |
|:-----------:|:------------:|:--:|:--:|
| States of Nature | 15-amp wire | 20-amp wire | 30-amp wire |
| 15-amp peak | 1 | 2 | 3 |
| 20-amp peak | 5 | 2 | 3 |
| 30-amp peak | 7 | 5 | 3 |

In [57]:
import numpy as np
loss = np.array([
    [1, 2, 3],
    [5, 2, 3],
    [7, 6, 3]
])

After deciding on the cost of each possible outcome, the contractor decides they can reduce the amount of risk they take on by giving families questionnaires. Suppose that the contractor asks each family to read the following question and check exactly one answer.

*How much electricity would you say your family draws on average?*
* 10-amp _____
* 12-amp _____
* 15-amp _____
* 20-amp _____

After doing this for some time, the electrical contractor learns the approximate frequency of a family's answer depending on  their peak amperage.

#### Conditional Probability of Questionnaire Answers Given State of Nature
| | | Questionnaire Outcomes | | |
|----|--------|--------|--------|--------|
| States of Nature | 10-amp answer | 12-amp answer | 15-amp answer | 20-amp answer
| 15-amp peak | 1/2 | 1/2 | 0 | 0 |
| 20-amp peak | 0 | 1/2 | 1/2 | 0 |
| 30-amp peak | 0 | 0 | 1/3 | 2/3 |

Notice that each row is a conditional distribution that sums to 1,  the probability of a family answering a certain way given their state of nature.

In [58]:
# They call this the "frequency of response table"
x_given_theta = np.array([
    [1/2, 1/2, 0,   0],
    [0,   1/2, 1/2, 0],
    [0,   0,   1/3, 2/3]
]) # P(theta|x)

The electrical contractor now has a tool to acquire information so they can determine the best action given the result of the family's questionnaire. In other words, depending on family's answer, the contractor can make some statement about the expected peak consumption of the family and what they might expect to lose for any action they take. The contractor may select any action, but through experience and preference eventually they will likely settle on a specific *strategy*, a permutation of actions to perform according to the family's questionnaire result.

In this case, there are 4 possible outcomes to the experiment and 4 possible actions to take for each outcome which leads to 16 total possible strategies. The set of strategies will be notated as $S$. These will be written as $s = (a_i, a_j, a_k, a_l)$. For example, $s1 = (15,15,20,30)$ is notation for Strategy 1 which is:
* When the family responds with 10-amp average, wire the house with 15-amp wire
* When the family responds with 12-amp average, wire the house with 15-amp wire
* When the family responds with 15-amp average, wire the house with 20-amp wire
* When the family responds with 20-amp average, wire the house with 30-amp wire

In contrast, $s2 = (30,30,20,15)$ tells us that Strategy 2 is:
* When the family responds with 10-amp average, wire the house with 30-amp wire
* When the family responds with 12-amp average, wire the house with 30-amp wire
* When the family responds with 15-amp average, wire the house with 20-amp wire
* When the family responds with 20-amp average, wire the house with 15-amp wire

In [59]:
strat1 = np.array([0, 0, 1, 2]) # Strategy 1 where the values represent the index of the actions
strat2 = np.array([2, 2, 1, 0]) # Strategy 2 ...

How can we evaluate the effectiveness of each strategy? Knowing what we do about the relationship between experiment outcomes and states of nature, the contractor should have some idea of the loss they can expect to see from each action in their strategy. For now, let us assume that the frequencies of each state of nature are equal, $\theta = (\frac{1}{3}, \frac{1}{3}, \frac{1}{3})$ and then we will determine the expected loss for each strategy given a state of nature.

In [60]:
loss[:,strat1]

array([[1, 1, 2, 3],
       [5, 5, 2, 3],
       [7, 7, 6, 3]])

In [61]:
x_given_theta

array([[0.5       , 0.5       , 0.        , 0.        ],
       [0.        , 0.5       , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333, 0.66666667]])

In [62]:
e_loss_given_theta1 = (x_given_theta * loss[:,strat1]).sum(axis=1)
e_loss_given_theta2 = (x_given_theta * loss[:,strat2]).sum(axis=1)

In [67]:
e_loss_given_theta1

array([1. , 3.5, 4. ])

In [68]:
e_loss_given_theta2

array([3.        , 2.5       , 6.66666667])

However, the expected total loss of a strategy is actually dependent on the frequency of the states of nature.

In [69]:
theta = np.array([1/3, 1/3, 1/3])
e_total_loss1 = (e_loss_given_theta1 * theta).sum()
e_total_loss2 = (e_loss_given_theta2 * theta).sum()
e_total_loss1, e_total_loss2

(2.833333333333333, 4.055555555555555)

In [70]:
theta = np.array([.9, .1, 0.])
e_total_loss1 = (e_loss_given_theta1 * theta).sum()
e_total_loss2 = (e_loss_given_theta2 * theta).sum()
e_total_loss1, e_total_loss2

(1.25, 2.95)

Explain minimax etc.

In [36]:
# Using Bayes' Rule to find expected loss given the answer to the questionnaire
state_freq = np.array([1/3, 1/3, 1/3]).reshape((-1,1)) # P(theta)
joint_freq = state_freq.reshape((-1,1)) * theta_given_x
x_freq = joint_freq.sum(axis=0)
theta_given_x = joint_freq / x_freq
s1_loss = (theta_given_x*loss[:,s1]).sum(axis=0)
s2_loss = (theta_given_x*loss[:,s2]).sum(axis=0)

In [71]:
# I will add things as they become necessary